{
  "_$ver": 1,
  "_$id": "w3oo9tbb",
  "_$type": "Scene",
  "left": 0,
  "right": 0,
  "top": 0,
  "bottom": 0,
  "name": "Scene2D",
  "width": 1334,
  "height": 750,
  "_$child": [
    {
      "_$id": "qz4djekj",
      "_$type": "Area2D",
      "name": "Area2D",
      "x": 435,
      "y": 279,
      "width": 600,
      "height": 400,
      "_$child": [
        {
          "_$id": "2uyq11ys",
          "_$type": "Sprite",
          "name": "TileMapLayer",
          "x": 135,
          "y": 4,
          "width": 100,
          "height": 100,
          "_$comp": [
            {
              "_$type": "TileMapLayer",
              "layer": 0,
              "chunkDatas": {
                "0": {
                  "0": {
                    "_$type": "TileMapChunkData",
                    "chunkX": 0,
                    "chunkY": 0,
                    "compressData": {
                      "65536": [
                        0,
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        32,
                        33,
                        34,
                        35,
                        36,
                        37,
                        38,
                        39,
                        40,
                        41,
                        42,
                        43,
                        64,
                        65,
                        66,
                        67,
                        68,
                        69,
                        70,
                        71,
                        72,
                        73,
                        74,
                        75,
                        96,
                        97,
                        98,
                        99,
                        100,
                        101,
                        102,
                        103,
                        104,
                        105,
                        106,
                        107,
                        128,
                        129,
                        130,
                        131,
                        132,
                        133,
                        134,
                        135,
                        136,
                        137,
                        138,
                        139,
                        160,
                        161,
                        162,
                        163,
                        164,
                        165,
                        166,
                        167,
                        168,
                        169,
                        170,
                        171,
                        192,
                        193,
                        194,
                        195,
                        196,
                        197,
                        198,
                        199,
                        200,
                        201,
                        202,
                        203,
                        224,
                        225,
                        226,
                        227,
                        228,
                        229,
                        230,
                        231,
                        232,
                        233,
                        234,
                        235,
                        256,
                        257,
                        258,
                        259,
                        260,
                        261,
                        262,
                        263,
                        264,
                        265,
                        266,
                        267,
                        268,
                        269,
                        270,
                        288,
                        289,
                        290,
                        291,
                        292,
                        293,
                        294,
                        295,
                        296,
                        297,
                        298,
                        299,
                        300,
                        301,
                        302,
                        320,
                        321,
                        322,
                        323,
                        324,
                        325,
                        326,
                        327,
                        328,
                        329,
                        330,
                        331,
                        332,
                        333,
                        334,
                        352,
                        353,
                        354,
                        355,
                        356,
                        357,
                        358,
                        359,
                        360,
                        361,
                        362,
                        363,
                        364,
                        365,
                        366,
                        12,
                        13,
                        14,
                        44,
                        45,
                        46,
                        76,
                        77,
                        78,
                        108,
                        109,
                        110,
                        140,
                        141,
                        142,
                        172,
                        173,
                        174,
                        204,
                        205,
                        206,
                        236,
                        237,
                        238
                      ],
                      "_$type": "Record"
                    },
                    "transFlags": {
                      "_$type": "Record"
                    }
                  },
                  "_$type": "Record",
                  "-1": {
                    "_$type": "TileMapChunkData",
                    "chunkX": -1,
                    "chunkY": 0,
                    "compressData": {
                      "65536": [
                        23,
                        24,
                        25,
                        26,
                        27,
                        28,
                        29,
                        30,
                        31,
                        55,
                        56,
                        57,
                        58,
                        59,
                        60,
                        61,
                        62,
                        63,
                        87,
                        88,
                        89,
                        90,
                        91,
                        92,
                        93,
                        94,
                        95,
                        119,
                        120,
                        121,
                        122,
                        123,
                        124,
                        125,
                        126,
                        127,
                        151,
                        152,
                        153,
                        154,
                        155,
                        156,
                        157,
                        158,
                        159,
                        183,
                        184,
                        185,
                        186,
                        187,
                        188,
                        189,
                        190,
                        191,
                        215,
                        216,
                        217,
                        218,
                        219,
                        220,
                        221,
                        222,
                        223,
                        247,
                        248,
                        249,
                        250,
                        251,
                        252,
                        253,
                        254,
                        255,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        46,
                        47,
                        48,
                        49,
                        50,
                        51,
                        52,
                        53,
                        54,
                        78,
                        79,
                        80,
                        81,
                        82,
                        83,
                        84,
                        85,
                        86,
                        110,
                        111,
                        112,
                        113,
                        114,
                        115,
                        116,
                        117,
                        118,
                        142,
                        143,
                        144,
                        145,
                        146,
                        147,
                        148,
                        149,
                        150,
                        174,
                        175,
                        176,
                        177,
                        178,
                        179,
                        180,
                        181,
                        182,
                        206,
                        207,
                        208,
                        209,
                        210,
                        211,
                        212,
                        213,
                        214,
                        238,
                        239,
                        240,
                        241,
                        242,
                        243,
                        244,
                        245,
                        246,
                        270,
                        271,
                        272,
                        273,
                        274,
                        275,
                        276,
                        277,
                        278,
                        279,
                        280,
                        281,
                        282,
                        302,
                        303,
                        304,
                        305,
                        306,
                        307,
                        308,
                        309,
                        310,
                        311,
                        312,
                        313,
                        314,
                        334,
                        335,
                        336,
                        337,
                        338,
                        339,
                        340,
                        341,
                        342,
                        343,
                        344,
                        345,
                        346,
                        366,
                        367,
                        368,
                        369,
                        370,
                        371,
                        372,
                        373,
                        374,
                        375,
                        376,
                        377,
                        378,
                        283,
                        284,
                        285,
                        286,
                        287,
                        315,
                        316,
                        317,
                        318,
                        319,
                        347,
                        348,
                        349,
                        350,
                        351,
                        379,
                        380,
                        381,
                        382,
                        383
                      ],
                      "_$type": "Record"
                    },
                    "transFlags": {
                      "_$type": "Record"
                    }
                  }
                },
                "_$type": "Record",
                "-1": {
                  "0": {
                    "_$type": "TileMapChunkData",
                    "chunkX": 0,
                    "chunkY": -1,
                    "compressData": {
                      "65536": [
                        864,
                        865,
                        866,
                        867,
                        868,
                        869,
                        870,
                        871,
                        872,
                        873,
                        874,
                        875,
                        896,
                        897,
                        898,
                        899,
                        900,
                        901,
                        902,
                        903,
                        904,
                        905,
                        906,
                        907,
                        928,
                        929,
                        930,
                        931,
                        932,
                        933,
                        934,
                        935,
                        936,
                        937,
                        938,
                        939,
                        960,
                        961,
                        962,
                        963,
                        964,
                        965,
                        966,
                        967,
                        968,
                        969,
                        970,
                        971,
                        992,
                        993,
                        994,
                        995,
                        996,
                        997,
                        998,
                        999,
                        1000,
                        1001,
                        1002,
                        1003,
                        672,
                        673,
                        674,
                        675,
                        676,
                        677,
                        678,
                        679,
                        680,
                        681,
                        682,
                        683,
                        684,
                        685,
                        686,
                        704,
                        705,
                        706,
                        707,
                        708,
                        709,
                        710,
                        711,
                        712,
                        713,
                        714,
                        715,
                        716,
                        717,
                        718,
                        736,
                        737,
                        738,
                        739,
                        740,
                        741,
                        742,
                        743,
                        744,
                        745,
                        746,
                        747,
                        748,
                        749,
                        750,
                        768,
                        769,
                        770,
                        771,
                        772,
                        773,
                        774,
                        775,
                        776,
                        777,
                        778,
                        779,
                        780,
                        781,
                        782,
                        800,
                        801,
                        802,
                        803,
                        804,
                        805,
                        806,
                        807,
                        808,
                        809,
                        810,
                        811,
                        812,
                        813,
                        814,
                        832,
                        833,
                        834,
                        835,
                        836,
                        837,
                        838,
                        839,
                        840,
                        841,
                        842,
                        843,
                        844,
                        845,
                        846,
                        876,
                        877,
                        878,
                        908,
                        909,
                        910,
                        940,
                        941,
                        942,
                        972,
                        973,
                        974,
                        1004,
                        1005,
                        1006
                      ],
                      "_$type": "Record"
                    },
                    "transFlags": {
                      "_$type": "Record"
                    }
                  },
                  "_$type": "Record",
                  "-1": {
                    "_$type": "TileMapChunkData",
                    "chunkX": -1,
                    "chunkY": -1,
                    "compressData": {
                      "65536": [
                        887,
                        888,
                        889,
                        890,
                        891,
                        892,
                        893,
                        894,
                        895,
                        919,
                        920,
                        921,
                        922,
                        923,
                        924,
                        925,
                        926,
                        927,
                        951,
                        952,
                        953,
                        954,
                        955,
                        956,
                        957,
                        958,
                        959,
                        983,
                        984,
                        985,
                        986,
                        987,
                        988,
                        989,
                        990,
                        991,
                        1015,
                        1016,
                        1017,
                        1018,
                        1019,
                        1020,
                        1021,
                        1022,
                        1023,
                        718,
                        719,
                        720,
                        721,
                        722,
                        723,
                        724,
                        725,
                        726,
                        727,
                        728,
                        729,
                        730,
                        750,
                        751,
                        752,
                        753,
                        754,
                        755,
                        756,
                        757,
                        758,
                        759,
                        760,
                        761,
                        762,
                        782,
                        783,
                        784,
                        785,
                        786,
                        787,
                        788,
                        789,
                        790,
                        791,
                        792,
                        793,
                        794,
                        814,
                        815,
                        816,
                        817,
                        818,
                        819,
                        820,
                        821,
                        822,
                        823,
                        824,
                        825,
                        826,
                        846,
                        847,
                        848,
                        849,
                        850,
                        851,
                        852,
                        853,
                        854,
                        855,
                        856,
                        857,
                        858,
                        878,
                        879,
                        880,
                        881,
                        882,
                        883,
                        884,
                        885,
                        886,
                        910,
                        911,
                        912,
                        913,
                        914,
                        915,
                        916,
                        917,
                        918,
                        942,
                        943,
                        944,
                        945,
                        946,
                        947,
                        948,
                        949,
                        950,
                        974,
                        975,
                        976,
                        977,
                        978,
                        979,
                        980,
                        981,
                        982,
                        1006,
                        1007,
                        1008,
                        1009,
                        1010,
                        1011,
                        1012,
                        1013,
                        1014,
                        699,
                        700,
                        701,
                        702,
                        703,
                        731,
                        732,
                        733,
                        734,
                        735,
                        763,
                        764,
                        765,
                        766,
                        767,
                        795,
                        796,
                        797,
                        798,
                        799,
                        827,
                        828,
                        829,
                        830,
                        831,
                        859,
                        860,
                        861,
                        862,
                        863,
                        686,
                        687,
                        688,
                        689,
                        690,
                        691,
                        692,
                        693,
                        694,
                        695,
                        696,
                        697,
                        698
                      ],
                      "_$type": "Record"
                    },
                    "transFlags": {
                      "_$type": "Record"
                    }
                  }
                }
              }
            }
          ]
        },
        {
          "_$id": "meoou8wa",
          "_$type": "Sprite",
          "name": "DecorateLayer",
          "x": 122,
          "y": -15,
          "width": 100,
          "height": 100
        }
      ]
    },
    {
      "_$id": "y8e6vyis",
      "_$type": "Sprite",
      "name": "UILayer",
      "width": 100,
      "height": 100,
      "_$child": [
        {
          "_$id": "lobby_chrome",
          "_$type": "Sprite",
          "name": "LobbyChrome",
          "width": 1334,
          "height": 750,
          "_mouseState": 1,
          "_$child": [
            {
              "_$id": "lobby_backdrop",
              "_$type": "GWidget",
              "name": "BackdropShade",
              "width": 1334,
              "height": 750,
              "alpha": 0.58,
              "_mouseState": 1,
              "background": {
                "_$type": "DrawRectCmd",
                "lineWidth": 1,
                "lineColor": "#111615",
                "fillColor": "#111615"
              }
            },
            {
              "_$id": "lobby_left_panel",
              "_$type": "GWidget",
              "name": "LeftMenuPanel",
              "x": 22,
              "y": 124,
              "width": 238,
              "height": 405,
              "alpha": 0.9,
              "_mouseState": 1,
              "background": {
                "_$type": "DrawRectCmd",
                "lineWidth": 1,
                "lineColor": "#34433e",
                "fillColor": "#111917"
              }
            },
            {
              "_$id": "lobby_left_accent",
              "_$type": "GWidget",
              "name": "LeftAccent",
              "x": 22,
              "y": 124,
              "width": 4,
              "height": 405,
              "_mouseState": 1,
              "background": {
                "_$type": "DrawRectCmd",
                "lineWidth": 1,
                "lineColor": "#b5a56f",
                "fillColor": "#b5a56f"
              }
            },
            {
              "_$id": "lobby_left_title",
              "_$type": "Text",
              "name": "LeftMenuTitle",
              "x": 44,
              "y": 136,
              "width": 190,
              "height": 32,
              "_mouseState": 1,
              "text": "整备功能",
              "font": "Microsoft YaHei",
              "fontSize": 21,
              "color": "#c8c4b5",
              "bold": true,
              "leading": 2,
              "letterSpacing": 0
            },
            {
              "_$id": "lobby_top_panel",
              "_$type": "GWidget",
              "name": "TopStatusPanel",
              "x": 370,
              "y": 22,
              "width": 565,
              "height": 66,
              "alpha": 0.9,
              "_mouseState": 1,
              "background": {
                "_$type": "DrawRectCmd",
                "lineWidth": 1,
                "lineColor": "#35433f",
                "fillColor": "#141b1a"
              }
            },
            {
              "_$id": "lobby_scene_title",
              "_$type": "Text",
              "name": "SceneTitle",
              "x": 398,
              "y": 31,
              "width": 260,
              "height": 28,
              "_mouseState": 1,
              "text": "安全区 · 整备大厅",
              "font": "Microsoft YaHei",
              "fontSize": 22,
              "color": "#eee9d9",
              "bold": true,
              "leading": 2,
              "letterSpacing": 0
            },
            {
              "_$id": "lobby_scene_subtitle",
              "_$type": "Text",
              "name": "SceneSubtitle",
              "x": 399,
              "y": 59,
              "width": 370,
              "height": 20,
              "_mouseState": 1,
              "text": "SURVIVAL PREPARATION / 生存准备",
              "font": "Microsoft YaHei",
              "fontSize": 12,
              "color": "#87928d",
              "leading": 2,
              "letterSpacing": 0
            },
            {
              "_$id": "lobby_right_panel",
              "_$type": "GWidget",
              "name": "ActionPanel",
              "x": 1030,
              "y": 142,
              "width": 278,
              "height": 365,
              "alpha": 0.9,
              "_mouseState": 1,
              "background": {
                "_$type": "DrawRectCmd",
                "lineWidth": 1,
                "lineColor": "#34433e",
                "fillColor": "#111917"
              }
            },
            {
              "_$id": "lobby_action_title",
              "_$type": "Text",
              "name": "ActionTitle",
              "x": 1054,
              "y": 157,
              "width": 220,
              "height": 30,
              "_mouseState": 1,
              "text": "行动中心",
              "font": "Microsoft YaHei",
              "fontSize": 22,
              "color": "#eee9d9",
              "bold": true,
              "leading": 2,
              "letterSpacing": 0
            },
            {
              "_$id": "lobby_action_hint",
              "_$type": "Text",
              "name": "ActionHint",
              "x": 1055,
              "y": 186,
              "width": 225,
              "height": 42,
              "_mouseState": 1,
              "text": "检查补给与消息，然后选择区域开始探索",
              "font": "Microsoft YaHei",
              "fontSize": 13,
              "color": "#8e9a94",
              "wordWrap": true,
              "leading": 5,
              "letterSpacing": 0
            }
          ]
        },
        {
          "_$id": "mubhrxi2",
          "_$type": "Sprite",
          "name": "button",
          "width": 100,
          "height": 100,
          "_$child": [
            {
              "_$id": "at5wnocg",
              "_$prefab": "e5f6cdc4-8abc-4212-b51b-3127183b1042",
              "name": "OpenSprite",
              "active": true,
              "x": 1068,
              "y": 594,
              "scaleX": 1.16,
              "scaleY": 1,
              "visible": true,
              "_$comp": [
                {
                  "_$override": "2938a217-4272-4f6d-aaf2-984b61320b26",
                  "targetNode": {
                    "_$ref": "lessrwbh"
                  }
                }
              ],
              "_$child": [
                {
                  "_$override": "6k3sv098",
                  "text": "外出探索",
                  "color": "#eee9d9"
                }
              ]
            },
            {
              "_$id": "3dmjv2yk",
              "_$prefab": "e5f6cdc4-8abc-4212-b51b-3127183b1042",
              "name": "OpenSprite_1",
              "active": true,
              "x": 42,
              "y": 409,
              "scaleX": 0.9,
              "scaleY": 0.78,
              "visible": true,
              "_$comp": [
                {
                  "_$override": "2938a217-4272-4f6d-aaf2-984b61320b26",
                  "targetNode": {
                    "_$ref": "uqx658op"
                  }
                }
              ],
              "_$child": [
                {
                  "_$override": "6k3sv098",
                  "text": "工作间",
                  "color": "#eee9d9"
                }
              ]
            },
            {
              "_$id": "h79bmpvd",
              "_$prefab": "e5f6cdc4-8abc-4212-b51b-3127183b1042",
              "name": "OpenSprite_2",
              "active": true,
              "x": 65,
              "y": 0,
              "visible": false,
              "_$comp": [
                {
                  "_$override": "2938a217-4272-4f6d-aaf2-984b61320b26",
                  "targetNode": {
                    "_$ref": "lamtt9s2"
                  }
                }
              ],
              "_$child": [
                {
                  "_$override": "6k3sv098",
                  "text": "商城",
                  "color": "#eee9d9"
                }
              ]
            },
            {
              "_$id": "ck42nxn7",
              "_$prefab": "e5f6cdc4-8abc-4212-b51b-3127183b1042",
              "name": "OpenSprite_3",
              "active": true,
              "x": 42,
              "y": 249,
              "scaleX": 0.9,
              "scaleY": 0.78,
              "visible": true,
              "_$comp": [
                {
                  "_$override": "2938a217-4272-4f6d-aaf2-984b61320b26",
                  "targetNode": {
                    "_$ref": "h6z6s76v"
                  }
                }
              ],
              "_$child": [
                {
                  "_$override": "6k3sv098",
                  "text": "每日签到",
                  "color": "#eee9d9"
                }
              ]
            },
            {
              "_$id": "6zyxbh28",
              "_$prefab": "e5f6cdc4-8abc-4212-b51b-3127183b1042",
              "name": "OpenSprite_4",
              "active": true,
              "x": 309,
              "y": 0,
              "visible": false,
              "_$comp": [
                {
                  "_$override": "2938a217-4272-4f6d-aaf2-984b61320b26",
                  "targetNode": {
                    "_$ref": "5voabxsh"
                  }
                }
              ],
              "_$child": [
                {
                  "_$override": "6k3sv098",
                  "text": "战令",
                  "color": "#eee9d9"
                }
              ]
            },
            {
              "_$id": "5d3fujtq",
              "_$prefab": "e5f6cdc4-8abc-4212-b51b-3127183b1042",
              "name": "OpenSprite_5",
              "active": true,
              "x": 42,
              "y": 329,
              "scaleX": 0.9,
              "scaleY": 0.78,
              "visible": true,
              "_$comp": [
                {
                  "_$override": "2938a217-4272-4f6d-aaf2-984b61320b26",
                  "targetNode": {
                    "_$ref": "vit9oqss"
                  }
                }
              ],
              "_$child": [
                {
                  "_$override": "6k3sv098",
                  "text": "仓库",
                  "color": "#eee9d9"
                }
              ]
            },
            {
              "_$id": "gebxfo6v",
              "_$prefab": "7f94452e-acc7-43a7-8e9c-27fe070a2873",
              "name": "buttonmodule_2",
              "active": true,
              "x": 1054,
              "y": 242,
              "visible": true,
              "_$comp": [
                {
                  "_$type": "2938a217-4272-4f6d-aaf2-984b61320b26",
                  "scriptPath": "../src/OpenSprite.ts",
                  "targetNode": {
                    "_$ref": "6n0rq07u"
                  },
                  "actionId": ""
                }
              ],
              "_$child": [
                {
                  "_$override": "tz6yo96j",
                  "text": "福利",
                  "color": "#eee9d9"
                },
                {
                  "_$override": "n392fqkh",
                  "visible": true
                }
              ]
            },
            {
              "_$id": "lk32kav8",
              "_$prefab": "e5f6cdc4-8abc-4212-b51b-3127183b1042",
              "name": "OpenSprite_6",
              "active": true,
              "x": 42,
              "y": 169,
              "scaleX": 0.9,
              "scaleY": 0.78,
              "visible": true,
              "_$comp": [
                {
                  "_$override": "2938a217-4272-4f6d-aaf2-984b61320b26",
                  "targetNode": {
                    "_$ref": "1cqsy2kf"
                  }
                }
              ],
              "_$child": [
                {
                  "_$override": "6k3sv098",
                  "text": "邮箱",
                  "color": "#eee9d9"
                }
              ]
            },
            {
              "_$id": "ehmqv3fy",
              "_$prefab": "7f94452e-acc7-43a7-8e9c-27fe070a2873",
              "name": "buttonmodule_3",
              "active": true,
              "x": 1172,
              "y": 242,
              "visible": true,
              "_$comp": [
                {
                  "_$type": "01a5fb0e-cb2e-46ce-aa80-cf85c829b7c6",
                  "scriptPath": "../src/douyin/AddDesktopButton.ts",
                  "buttonNode": {
                    "_$ref": "ehmqv3fy"
                  }
                }
              ],
              "_$child": [
                {
                  "_$override": "tz6yo96j",
                  "text": "添加\n桌面",
                  "color": "#eee9d9"
                },
                {
                  "_$override": "n392fqkh",
                  "visible": true
                }
              ]
            },
            {
              "_$id": "d57e1jd3",
              "_$prefab": "7f94452e-acc7-43a7-8e9c-27fe070a2873",
              "name": "buttonmodule_4",
              "active": true,
              "x": 1054,
              "y": 354,
              "visible": true,
              "_$comp": [
                {
                  "_$type": "13b8da6b-cda3-4de5-9390-45c2a8752821",
                  "scriptPath": "../src/douyin/SubscribeButton.ts",
                  "buttonNode": {
                    "_$ref": "d57e1jd3"
                  },
                  "templateId": "MSG22029227137307674382952511359247"
                }
              ],
              "_$child": [
                {
                  "_$override": "tz6yo96j",
                  "text": "消息\n订阅",
                  "color": "#eee9d9"
                },
                {
                  "_$override": "n392fqkh",
                  "visible": true
                }
              ]
            }
          ]
        },
        {
          "_$id": "fm9nno5m",
          "_$type": "Sprite",
          "name": "panel",
          "width": 100,
          "height": 100,
          "_$child": [
            {
              "_$id": "lessrwbh",
              "_$prefab": "73ecaedc-782b-45f4-9ec4-b0ab7333b96c",
              "name": "mapchoose",
              "active": true,
              "x": 0,
              "y": 0,
              "visible": false
            },
            {
              "_$id": "vit9oqss",
              "_$prefab": "9bf2effb-3f48-4c83-8ac7-38f62f17e5a2",
              "name": "warehouse_panel",
              "active": true,
              "x": 0,
              "y": 0,
              "visible": false
            },
            {
              "_$id": "uqx658op",
              "_$prefab": "ba7354b5-c50c-400f-8dc6-7010cb184079",
              "name": "CraftingPanel",
              "active": true,
              "x": 0,
              "y": 0,
              "visible": false,
              "_$child": [
                {
                  "_$override": "57r39bvn",
                  "scroller": {
                    "_$type": "Scroller",
                    "barDisplay": 5,
                    "vScrollBarRes": {
                      "_$uuid": "eb7cd798-7a10-46c5-b85f-cdc935a78181",
                      "_$type": "Prefab"
                    }
                  },
                  "background": {
                    "_$type": "DrawRoundRectCmd",
                    "lineWidth": 1,
                    "lineColor": "#647565",
                    "fillColor": "#293832"
                  },
                  "width": 111
                },
                {
                  "_$override": "joiii0ex",
                  "_$comp": [
                    {
                      "_$override": "14d09e1b-aa6f-4bcf-afc1-cf0226a43024",
                      "targetNode": {
                        "_$ref": "uqx658op"
                      }
                    }
                  ]
                }
              ]
            },
            {
              "_$id": "t6lrfgse",
              "_$prefab": "8ae45e30-f989-4f5e-b586-6e6c4cdbaaee",
              "name": "bag_panel",
              "active": true,
              "x": 0,
              "y": 0,
              "visible": false
            },
            {
              "_$id": "6n0rq07u",
              "_$prefab": "b26eb433-8357-43fb-8dfb-54e3018200df",
              "name": "SidePanel",
              "active": true,
              "x": 476,
              "y": 155,
              "width": 400,
              "height": 400,
              "visible": false
            },
            {
              "_$id": "1cqsy2kf",
              "_$prefab": "a59fd96f-ba7b-4f76-9899-82f97c113bd7",
              "name": "MailPanel",
              "active": true,
              "x": 0,
              "y": 0,
              "visible": false,
              "alpha": 1,
              "_$comp": [
                {
                  "_$override": "7f7b2a1a-0d2d-4f07-8b2d-2df6fef0a4a1",
                  "rewardTargetNode": {
                    "_$ref": [
                      "1cqsy2kf",
                      "kf7cmfk3",
                      "sbsnrylr"
                    ]
                  },
                  "messageText": {
                    "_$ref": "iczt30jd"
                  }
                }
              ],
              "_$child": [
                {
                  "_$override": "9bryjchh",
                  "_$comp": [
                    {
                      "_$override": "0f3d3c58-9d25-4a96-a2b5-4dcf1c5f3f71",
                      "templateNode": {
                        "_$ref": [
                          "1cqsy2kf",
                          "kf7cmfk3"
                        ]
                      }
                    }
                  ]
                }
              ]
            },
            {
              "_$id": "5voabxsh",
              "_$prefab": "f7c68002-452f-476a-8f0b-23cae147ab6c",
              "name": "battlepass_panel",
              "active": true,
              "x": 0,
              "y": 0,
              "visible": false
            },
            {
              "_$id": "h6z6s76v",
              "_$prefab": "e44dba20-104c-4b36-9a31-db9de2fd93fe",
              "name": "sign_in_panel",
              "active": true,
              "x": 0,
              "y": 0,
              "visible": false
            },
            {
              "_$id": "lamtt9s2",
              "_$prefab": "12820c93-821e-4387-a85d-a11fec2970ed",
              "name": "ShopPanel",
              "active": false,
              "x": 0,
              "y": 0,
              "visible": false
            },
            {
              "_$id": "euevxv64",
              "_$prefab": "952f2456-5258-42ea-9928-7fa0dc233070",
              "name": "MakePanel",
              "active": true,
              "x": 0,
              "y": 0,
              "visible": false,
              "_$comp": [
                {
                  "_$override": "e7a82e0d-ec39-4ac1-9518-f70baf987b54",
                  "messageTextNode": {
                    "_$ref": "iczt30jd"
                  }
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "_$id": "4c5squ0r",
      "_$prefab": "5963ec7e-fa31-4699-9c4e-b09c35dca815",
      "name": "ad",
      "active": true,
      "x": 307,
      "y": 294,
      "visible": false,
      "_$comp": [
        {
          "_$override": "9c1f431e-702b-42bf-90f0-04f0f7e01a13",
          "buttonNode": {
            "_$ref": "4c5squ0r"
          }
        }
      ]
    },
    {
      "_$id": "5abopbdc",
      "_$type": "Sprite",
      "name": "text",
      "width": 100,
      "height": 100,
      "_$child": [
        {
          "_$id": "iczt30jd",
          "_$type": "Text",
          "name": "broadcast",
          "width": 1334,
          "height": 750,
          "text": "Text",
          "fontSize": 40,
          "color": "#000000",
          "bold": true,
          "align": "center",
          "valign": "middle",
          "leading": 2,
          "letterSpacing": 0
        }
      ]
    }
  ]
}