const { regClass, property } = Laya;

/** Small vertex effects for forest plants generated by decoration area Prefabs. */
@regClass("b38c8c9f-4382-48a4-904d-29878f66a31b")
export class ForestDecorationShader extends Laya.Script {
    @property({ type: Number, caption: "效果（0 风摆，1 浮动）" }) public effect = 0;
    @property({ type: Number, caption: "幅度" }) public amplitude = 2;
    @property({ type: Number, caption: "相位" }) public phase = 0;

    private static registered = false;
    private static snowTexture: Laya.Texture | null = null;
    private static snowAmount = 0;
    private static readonly instances = new Set<ForestDecorationShader>();
    private material: Laya.Material | null = null;
    private original: Laya.Material | null = null;
    private elapsed = 0;
    private state = new Laya.Vector4();

    onStart(): void {
        const node = this.owner as Laya.Sprite, texture = node.texture;
        if (!texture) {
            console.warn("[ForestDecorationShader] Missing sprite texture; static decoration retained.");
            return;
        }
        ForestDecorationShader.register();
        this.original = node.material;
        const material = this.material = new Laya.Material();
        material.setShaderName("ForestDecorationVertexFX");
        material.cull = Laya.RenderState.CULL_NONE;
        material.shaderData.setVector(Laya.Shader3D.propertyNameToID("u_fxRect"),
            new Laya.Vector4(node.width, node.height, 0, 0));
        ForestDecorationShader.setSnowUniforms(material);
        ForestDecorationShader.instances.add(this);
        node.material = material;
        this.updateState();
    }

    onUpdate(): void {
        if (!this.material) return;
        this.elapsed += Math.min(0.1, Math.max(0, Laya.timer.delta) / 1000);
        this.updateState();
    }

    onDestroy(): void {
        ForestDecorationShader.instances.delete(this);
        const node = this.owner as Laya.Sprite;
        if (node && !node.destroyed && node.material === this.material) node.material = this.original;
        this.material?.destroy();
        this.material = null;
    }

    static setSnow(texture: Laya.Texture | null, amount: number): void {
        this.snowTexture = texture;
        this.snowAmount = Math.max(0, Math.min(1, amount));
        for (const instance of this.instances)
            if (instance.material) this.setSnowUniforms(instance.material);
    }

    private static setSnowUniforms(material: Laya.Material): void {
        const id = Laya.Shader3D.propertyNameToID;
        material.shaderData.setTexture(id("u_decorationSnowTexture"),
            this.snowTexture?.bitmap || Laya.Texture2D.whiteTexture);
        material.shaderData.setNumber(id("u_decorationSnowAmount"), this.snowAmount);
    }

    private updateState(): void {
        this.state.setValue(this.elapsed, this.effect, Math.max(0, this.amplitude), this.phase);
        this.material?.shaderData.setVector(Laya.Shader3D.propertyNameToID("u_fxState"), this.state);
        (this.owner as Laya.Sprite).repaint();
    }

    private static register(): void {
        if (this.registered) return;
        const shader = Laya.Shader3D.add("ForestDecorationVertexFX");
        shader.shaderType = Laya.ShaderFeatureType.D2_TextureSV;
        const sub = new Laya.SubShader({
            a_posuv: [0, Laya.ShaderDataType.Vector4],
            a_attribColor: [1, Laya.ShaderDataType.Vector4],
            a_attribFlags: [2, Laya.ShaderDataType.Vector4],
            a_customs: [3, Laya.ShaderDataType.Vector4]
        }, {
            u_fxRect: Laya.ShaderDataType.Vector4,
            u_fxState: Laya.ShaderDataType.Vector4,
            u_decorationSnowTexture: Laya.ShaderDataType.Texture2D,
            u_decorationSnowAmount: Laya.ShaderDataType.Float
        });
        shader.addSubShader(sub);
        sub.addShaderPass(`
            #include "Sprite2DVertex.glsl";
            varying vec2 v_snowLocal;
            void main() {
                vertexInfo info; getVertexInfo(info);
                v_texcoordAlpha=info.texcoordAlpha; v_color=info.color;
                v_useTex=info.useTex; v_useClip=info.useClip; v_customs=info.customs;
                #ifdef USE_TEX_ARRAY
                v_texLayer=a_attribFlags.w;
                #endif
                v_snowLocal=info.pos.xy;
                vec2 pos=info.pos;
                float fromBase=clamp(pos.y/max(1.0,u_fxRect.y),0.0,1.0);
                if (u_fxState.y<0.5) {
                    pos.x+=sin(u_fxState.x*1.35+u_fxState.w+fromBase*2.8)*u_fxState.z*fromBase*fromBase;
                } else {
                    pos.y+=sin(u_fxState.x*0.85+u_fxState.w)*u_fxState.z;
                }
                gl_Position=getPosition(pos);
            }`, `
            #if defined(GL_FRAGMENT_PRECISION_HIGH)
            precision highp float;
            #else
            precision mediump float;
            #endif
            #include "Sprite2DFrag.glsl";
            varying vec2 v_snowLocal;
            float snowHash(vec2 p) {
                p=fract(p*vec2(0.1031,0.11369));
                p+=dot(p,p.yx+19.19);
                return fract((p.x+p.y)*p.x);
            }
            float snowPatchNoise(vec2 p) {
                vec2 cell=floor(p), f=fract(p);
                f=f*f*(3.0-2.0*f);
                float a=snowHash(cell);
                float b=snowHash(cell+vec2(1.0,0.0));
                float c=snowHash(cell+vec2(0.0,1.0));
                float d=snowHash(cell+vec2(1.0,1.0));
                return mix(mix(a,b,f.x),mix(c,d,f.x),f.y);
            }
            float snowBlob(vec2 local, vec2 cell, vec2 center, float salt, float radius) {
                vec2 centerLocal=center*50.0;
                float edgeNoise=snowPatchNoise((local-centerLocal)/8.0+cell+vec2(salt,salt*1.73));
                float variedRadius=radius+(edgeNoise-0.5)*1.2;
                float distance=length(local-centerLocal);
                return 1.0-smoothstep(variedRadius-1.0,variedRadius+1.0,distance);
            }
            float snowPatchMask(vec2 local,float amount) {
                if(amount>0.98) return 1.0;
                vec2 cell=floor(local/50.0);
                float radius=7.25*sqrt(amount/0.2);
                vec2 j0=vec2(snowHash(cell+vec2(1.3,4.1)),snowHash(cell+vec2(8.7,2.6)))-0.5;
                vec2 j1=vec2(snowHash(cell+vec2(3.2,9.4)),snowHash(cell+vec2(7.1,5.8)))-0.5;
                vec2 j2=vec2(snowHash(cell+vec2(6.5,1.7)),snowHash(cell+vec2(2.4,8.3)))-0.5;
                float mask=snowBlob(local,cell,vec2(0.25,0.27)+j0*0.08,1.7,radius);
                mask=max(mask,snowBlob(local,cell,vec2(0.72,0.31)+j1*0.08,5.3,radius));
                mask=max(mask,snowBlob(local,cell,vec2(0.47,0.74)+j2*0.08,8.9,radius));
                return mask;
            }
            void main() {
                clip();
                vec4 color=getSpriteTextureColor();
                float amount=clamp(u_decorationSnowAmount,0.0,1.0);
                if (amount>0.0 && color.a>0.001) {
                    float mask=snowPatchMask(v_snowLocal,amount);
                    vec2 tile=1.0-abs(mod(v_snowLocal/64.0,2.0)-1.0);
                    vec4 snow=transspaceColor(texture2D(u_decorationSnowTexture,tile));
                    color.rgb=mix(color.rgb,snow.rgb*color.a,mask);
                }
                setglColor(color);
            }`);
        this.registered = true;
    }
}
